version: "3"
services:
  db:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_DB=tech_blog
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"

  app:
    build: .
    image: tajalislam/tech-forum
    depends_on:
      - db
    ports:
      - "3000:3000"


